exclude: \.min\.(js|css)(\.map)?$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast  # Simply check whether files parse as valid python.
        types: [python]
      - id: check-json  # Attempts to load all json files to verify syntax.
        types: [json]
      - id: check-toml  # Attempts to load all TOML files to verify syntax.
        types: [toml]
      - id: check-xml # Attempts to load all xml files to verify syntax.
        types: [xml]
      - id: check-yaml  # Attempts to load all yaml files to verify syntax.
        types: [yaml]
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline.
      # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-merge-conflict
      # Checks that all your JSON files are pretty. "Pretty" here means that keys are sorted and indented.
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: trailing-whitespace  # Trims trailing whitespace.
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/timothycrosley/isort  # isort your imports, so you don't have to.
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
        args:
          - --line-length=120
          - --profile=black
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        types: [python]
  # A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.1
    hooks:
      - id: ruff
